import subprocess
import pyautogui
import time
from datetime import datetime

def write_to_notepad(content: str, type: str = "general"):
    """Write content to notepad with formatting"""
    try:
        # Open notepad
        subprocess.Popen(['notepad.exe'])
        time.sleep(1)

        # Add header
        header = f"""
// Generated by RUDRA AI
// Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// Type: {type}

"""
        pyautogui.write(header)
        pyautogui.write(content)
        return True
    except Exception as e:
        print(f"❌ Notepad error: {e}")
        return False

def write_code(code: str, language: str):
    """Write code with proper formatting"""
    header = f"""
# {language.upper()} Code
# Generated by RUDRA AI
# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

"""
    return write_to_notepad(header + code, type="code")